"""初始建表

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 09:00:45.058215
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_openid'), ['openid'], unique=True)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('province', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('cooperated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_owner_id'), ['owner_id'], unique=False)

    op.create_table('store_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_corrections_store_id'), ['store_id'], unique=False)

    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('cooperated', sa.String(length=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('est_cost', sa.Float(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_user_id'), ['user_id'], unique=False)

    op.create_table('store_profile_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_visit_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_visit_id'], ['visits.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'key')
    )
    with op.batch_alter_table('store_profile_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_profile_sections_store_id'), ['store_id'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('acceptance', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'module')
    )
    with op.batch_alter_table('visit_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_analysis_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'seq')
    )
    with op.batch_alter_table('visit_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_segments_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_transcripts',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('utterances', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_transcripts')
    with op.batch_alter_table('visit_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_segments_visit_id'))

    op.drop_table('visit_segments')
    with op.batch_alter_table('visit_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_analysis_visit_id'))

    op.drop_table('visit_analysis')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_visit_id'))
        batch_op.drop_index(batch_op.f('ix_todos_user_id'))
        batch_op.drop_index(batch_op.f('ix_todos_store_id'))

    op.drop_table('todos')
    with op.batch_alter_table('store_profile_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_profile_sections_store_id'))

    op.drop_table('store_profile_sections')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_user_id'))
        batch_op.drop_index(batch_op.f('ix_visits_store_id'))
        batch_op.drop_index(batch_op.f('ix_visits_status'))
        batch_op.drop_index(batch_op.f('ix_visits_created_at'))

    op.drop_table('visits')
    with op.batch_alter_table('store_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_corrections_store_id'))

    op.drop_table('store_corrections')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_owner_id'))

    op.drop_table('stores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_openid'))

    op.drop_table('users')
    # ### end Alembic commands ###
