"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 03:29:09.036428
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('province', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('grid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wecom_added', sa.Boolean(), nullable=True),
    sa.Column('reported', sa.Boolean(), nullable=True),
    sa.Column('el_code', sa.String(length=64), nullable=False),
    sa.Column('service_station', sa.String(length=128), nullable=False),
    sa.Column('gift_tier', sa.String(length=32), nullable=False),
    sa.Column('monthly_sales', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_openid'), ['openid'], unique=True)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.Column('store_type', sa.String(length=32), nullable=False),
    sa.Column('cooperation_status', sa.String(length=16), nullable=False),
    sa.Column('primary_sales_id', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('grid', sa.String(length=64), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('wecom_added', sa.Boolean(), nullable=True),
    sa.Column('photo_key', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('feishu_record_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['store_directory.id'], ),
    sa.ForeignKeyConstraint(['primary_sales_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('platform', 'external_id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_primary_sales_id'), ['primary_sales_id'], unique=False)

    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('business_line', sa.String(length=32), nullable=True),
    sa.Column('cooperated', sa.String(length=4), nullable=True),
    sa.Column('purposes', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('store_condition', sa.String(length=32), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('checkin_address', sa.String(length=255), nullable=False),
    sa.Column('checkin_lat', sa.Float(), nullable=True),
    sa.Column('checkin_lng', sa.Float(), nullable=True),
    sa.Column('photo_key', sa.String(length=255), nullable=False),
    sa.Column('survey', sa.JSON(), nullable=True),
    sa.Column('recording_mode', sa.String(length=16), nullable=False),
    sa.Column('no_recording_reason', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('est_cost', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('legacy', sa.Boolean(), nullable=False),
    sa.Column('feishu_record_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_status'), ['status'], unique=False)
        batch_op.create_index('ix_visits_store_entered', ['store_id', 'entered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_visits_visitor_entered', ['visitor_id', 'entered_at'], unique=False)

    op.create_table('correction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('target_key', sa.String(length=32), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_events_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_events_visit_id'), ['visit_id'], unique=False)

    op.create_table('store_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_corrections_store_id'), ['store_id'], unique=False)

    op.create_table('store_profile_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('evidence', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('source_visit_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_visit_id'], ['visits.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'key')
    )
    with op.batch_alter_table('store_profile_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_profile_sections_store_id'), ['store_id'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('acceptance', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('target_qty', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('achieved_qty', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('progress_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('corrected_result', sa.JSON(), nullable=True),
    sa.Column('corrected_by', sa.Integer(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'module')
    )
    with op.batch_alter_table('visit_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_analysis_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('file_missing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'seq')
    )
    with op.batch_alter_table('visit_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_segments_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_transcripts',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('utterances', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_transcripts')
    with op.batch_alter_table('visit_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_segments_visit_id'))

    op.drop_table('visit_segments')
    with op.batch_alter_table('visit_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_analysis_visit_id'))

    op.drop_table('visit_analysis')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_visit_id'))
        batch_op.drop_index(batch_op.f('ix_todos_store_id'))
        batch_op.drop_index(batch_op.f('ix_todos_assignee_id'))

    op.drop_table('todos')
    with op.batch_alter_table('store_profile_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_profile_sections_store_id'))

    op.drop_table('store_profile_sections')
    with op.batch_alter_table('store_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_corrections_store_id'))

    op.drop_table('store_corrections')
    with op.batch_alter_table('correction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_events_visit_id'))
        batch_op.drop_index(batch_op.f('ix_correction_events_store_id'))

    op.drop_table('correction_events')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index('ix_visits_visitor_entered')
        batch_op.drop_index(batch_op.f('ix_visits_store_id'))
        batch_op.drop_index('ix_visits_store_entered')
        batch_op.drop_index(batch_op.f('ix_visits_status'))

    op.drop_table('visits')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_primary_sales_id'))
        batch_op.drop_index(batch_op.f('ix_stores_name'))

    op.drop_table('stores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_openid'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_manager_id'))

    op.drop_table('users')
    op.drop_table('store_directory')
    # ### end Alembic commands ###
